LILTHRIFTYSTORES/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', include('lilthriftyhub.urls')),
    path('admin/', admin.site.urls),
    path('plugmanager/', include('plugmanager.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('customer/', include('customer.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
  
from django.urls import path, re_path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


app_name = "accounts"

urlpatterns=[
    path('signup/customer/', views.CustomerSignUpView.as_view(), name="customer_signup"),
    path('signup/plugmanager/', views.ManagerSignUpView.as_view(), name="plugmanager_signup"),
	path('sign-in', views.SignInView.as_view(), name="sign-in"),
	path('sign-out', views.sign_out, name="sign-out"),
    path('profile/', views.get_user_profile, name="profile"),
    path('edit_profile', views.edit_profile, name="edit_profile"),
    path('login/customer/', views.loginView.as_view(), name="login"),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),


]

templates/cart.html
{% extends 'index.html' %}

{% load static %}
<body>

	
	{% block content %}
	{% block css %}
  <link rel="stylesheet" href="{%static 'styles/cart.css'%}">
	{% endblock %}
	{% block scripts %}
	<script type="text/javascript" src="{% static 'custom.js' %}"></script>
	{% endblock %}

  {% if totalitems %}
   <main>
    <div class="Cart">
      <div class="Cart-main">
        <h3 class="my-4 border-bottom pb-1">Items in Cart ({{totalitems}})</h3>
        <ul>
          <li class="item item-heading">Item</li>
          <li class="price">Price</li>
          <li class="quantity">Quantity</li>
          <li class="subtotal">Subtotal</li>
        </ul>
      </div>
      {% for product_id,item in cart_data.items %}
      <div class="Cart-Item">
        <div class="item">
          <div class="item-image">
            <img src="/media/{{item.image}}" width="50" class="product-frame" />
          </div>
          <div class="product-details">
            <h1><strong>{{item.product}}{{item.brand}}</strong> <a href="/product/{{item.title|slugify}}/{{product_id}}">{{item.title}}</a></h1>
            <p><strong>{{item.color}}, {{item.size}}</strong></p>
            <p>Product Code - {{product_id}}</p>

          </div>
        </div>
        <div class="price">price:$ {{item.price}}</div>
        <div class="quantity">
            <input type="number" class="product-qty-{{product_id}}" value="{{item.qty}}" style="vertical-align: bottom;" />
        </div>
        <div class="subtotal">subtotal:$ {% widthratio item.price 1 item.qty %}</div>
        <div class="remove">
          <a href=""><button class="update-item" data-item="{{product_id}}">Update</button></i></a>
					<a href=""><button class="delete-item" data-item="{{product_id}}"> Remove</button></a>    
        </div>
      </div>
      {% endfor %}
    </div>
    <aside>
      <div class="checkout">
        <div class="checkout-total-items"><span class="total-items"></span> Items in your Bag</div>
        <div class="checkout-subtotal">
          {% for product_id,item in cart_data.items %}
          <div class="item-in-cart">
            {{item.qty}} {{item.title}}
          </div>
          <div class="item-price">
            $ {% widthratio item.price 1 item.qty %}
          </div>
          {% endfor %}
          <div class="subtotal-title">Subtotal</div>
          <div class="subtotal-value final-value" id="Cart-subtotal">${{total_amt}}</div>
        </div>
        <div class="Delivery">
     <input type="text" class="Delivery-input" placeholder="Enter Delivery location">
        </div>
        <div class="checkout-total">
          <div class="shipping">Shipping cost</div>
          <div class="shipping-cost">100</div>
          <div class="total-title">Total</div>
          <div class="total-value final-value" id="Cart-total">${{sum_total_amt}}</div>
        </div>
        {% if totalitems %}
        <div class="Btn-checkout">
          <a href="{% url 'cart-checkout' %}" class="text-decoration-none"><button class="checkout-btn">Go to Secure Checkout</button></a>
          
        </div>
        {% endif %}
      </div>
    </aside>
  </main>
      {%else%}
  <main>
    <div class="Cart">
      <div class="Cart-main">
        <h3 class="my-4 border-bottom pb-1">No items added in cart </h3>
        <h3 class="">Items in cart {{totalitems}} </h3>
        <h3 class="">please add item in the  cart to proceed to checkout</h3>
      </div>
    </div>
  </main>
  {% endif %}

	{% endblock %}


</body>
</html>

templates/customer_signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>lil Thrifty</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'styles/registration/login.css'%}">
 	<!-- Main Jquery -->
  <meta charset="UTF-8">
  <!--iconify-->
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!--iconify-->
    <!--bootstrap css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
 <!--bootstrap css-->
<!--font awesome icons-->
<script src="https://kit.fontawesome.com/2f84532afd.js" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/a386d2646c.js" crossorigin="anonymous"></script>
<!--font awesome icons-->
<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>

  <!-- https://cdnjs.com/libraries/toastr.js/latest -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
  <div class="background_image"
  style="background-image:url({% static 'images/login.jpg' %})"></div>
<div class="container">
    <main>
      <div class="form signUp-form">
        <h2>Create Account</h2>

        <form id="signupform" method="POST" action="{% url 'accounts:customer_signup' %}">
            {% csrf_token %}
        
            
            <label for="first_name">First Name</label>
            {{form.first_name}}
        
            <label for="last_name">Last Name</label>
            {{form.last_name}}
        
            <label for="username">Username</label>
            {{form.username}}
        
            <label for="password1">Password</label>
            {{form.password1}}
        
            <label for="password2">Confirm Password</label>
            {{form.password2}}
        
            {{form.token}}
            <label class="check-container">Show Passwords
             <input type="checkbox" onclick="showPword()">
             <span class="checkmark"></span>
            </label>
        
            <button type="submit">Sign up</button>
        
          </form>
      </div>

      <div class="form signIn-form">
        <h2>Login</h2>
        <form id="signinform" method="POST" action="{% url 'accounts:sign-in' %}">
          {% csrf_token %}
            <label for="username">Username</label>
            {{form.username}}
        
            <label for="password">Password</label>
            {{form.password}}
        
            <label class="check-container">Show Passwords
             <input type="checkbox" onclick="showPword()">
             <span class="checkmark"></span>
           </label>
          <div class="forgot">
                <strong><a href="" class="  text-decoration-none" >Forgot password?</a> </strong>
          </div>

           <button type="submit">Sign in</button>
         </form>
      </div>
    </main>
    <aside>
      <div class="sign-in-block">
        <h2>Already a User?</h2>

        <button type="submit" id="sign-in-btn">Sign In</button>
      </div>
      <div class="sign-up-block">
        <h2>New User?</h2>

        <button type="submit" id="sign-up-btn">Sign Up</button>
      </div>
    </aside>
  </div>

</body>
<script type="text/javascript">
    // Create a variable that can be used in main.js
    var recaptcha_site_key = '{{recaptcha_site_key|safe}}'
  </script>
<script>
     const asideSection = document.querySelector("aside");
      const mainSection = document.querySelector("main");

      const signInBtn = document.getElementById("sign-in-btn");
      const signUpBtn = document.getElementById("sign-up-btn");

      signInBtn.addEventListener("click", () => {
        mainSection.classList.add("slideRight");
        asideSection.classList.add("slideLeft");
      });

      signUpBtn.addEventListener("click", () => {
        mainSection.classList.remove("slideRight");
        asideSection.classList.remove("slideLeft");
      });
</script>
<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- https://cdnjs.com/libraries/toastr.js/latest -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="{% static 'main.js' %}"></script>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>lil Thrifty</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'styles/registration/login.css'%}">
 	<!-- Main Jquery -->
  <meta charset="UTF-8">
  <!--iconify-->
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!--iconify-->
    <!--bootstrap css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
 <!--bootstrap css-->
<!--font awesome icons-->
<script src="https://kit.fontawesome.com/2f84532afd.js" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/a386d2646c.js" crossorigin="anonymous"></script>
<!--font awesome icons-->
<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>

  <!-- https://cdnjs.com/libraries/toastr.js/latest -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />



</head>
<body>
  <div class="background_image"
  style="background-image:url({% static 'images/login.jpg' %})"></div>
<div class="container">
    <main>
      <div class="form signUp-form">
        <h2>Login</h2>
        <form id="signinform" method="POST" action="{% url 'accounts:sign-in' %}">
          {% csrf_token %}
            <label for="username">Username</label>
            {{form.username}}
        
            <label for="password">Password</label>
            {{form.password}}
        
            <label class="check-container">Show Passwords
             <input type="checkbox" onclick="showPword()">
             <span class="checkmark"></span>
           </label>
          <div class="forgot">
                <strong><a href="" class="  text-decoration-none" >Forgot password?</a> </strong>
          </div>

           <button type="submit">Sign in</button>
         </form>
      </div>

      <div class="form signIn-form">
        <h2>Create Account</h2>

        <form id="signupform" method="POST" action="{% url 'accounts:customer_signup' %}">
          {% csrf_token %}
      
          
          <label for="first_name">First Name</label>
          {{form.first_name}}
      
          <label for="last_name">Last Name</label>
          {{form.last_name}}
      
          <label for="username">Username</label>
          {{form.username}}
      
          <label for="password1">Password</label>
          {{form.password1}}
      
          <label for="password2">Confirm Password</label>
          {{form.password2}}
      
          {{form.token}}
          <label class="check-container">Show Passwords
           <input type="checkbox" onclick="showPword()">
           <span class="checkmark"></span>
          </label>
      
          <button type="submit">Sign up</button>
      
        </form>
      
      </div>
    </main>
    <aside>
      <div class="sign-in-block">
        <h2>Already a User?</h2>

        <button type="submit" id="sign-in-btn">Sign Up</button>
      </div>
      <div class="sign-up-block">
        <h2>New User?</h2>

        <button type="submit" id="sign-up-btn">Login</button>
      </div>
    </aside>
  </div>

</body>
<script type="text/javascript">
    // Create a variable that can be used in main.js
    var recaptcha_site_key = '{{recaptcha_site_key|safe}}'
  </script>
<script>
     const asideSection = document.querySelector("aside");
      const mainSection = document.querySelector("main");

      const signInBtn = document.getElementById("sign-in-btn");
      const signUpBtn = document.getElementById("sign-up-btn");

      signInBtn.addEventListener("click", () => {
        mainSection.classList.add("slideRight");
        asideSection.classList.add("slideLeft");
      });

      signUpBtn.addEventListener("click", () => {
        mainSection.classList.remove("slideRight");
        asideSection.classList.remove("slideLeft");
      });
</script>
<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- https://cdnjs.com/libraries/toastr.js/latest -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="{% static 'main.js' %}"></script>
</html>

templates/orders.html
{% extends 'profile.html' %}

{% load static %}
{% block content %}

	<!-- main_adminpage -->
			<ul class="admin_stat">
				<li>
					<i class="icon uil uil-shopping-cart-alt"></i>
					<span class="text">
						<h3>1020</h3>
						<p>Orders</p>
					</span>
				</li>
				<li>
					<i class="icon uil uil-shop"></i>
					<span class="text">
						<h3>2834</h3>
						<p>store</p>
					</span>
				</li>
				<li>
					<i class="icon uil uil-cloud-upload"></i>
					<span class="text">
						<h3>2834</h3>
						<p>upload</p>
					</span>
				</li>
				<li>
					<i class="icon uil uil-bill"></i>
					<span class="text">
						<h3>$2543</h3>
						<p>Total Sales</p>
					</span>
				</li>
			</ul>


			<div class="order_nav">
				<div class="orders_available">
					<div class="order_title">
						<h3>Recent Orders</h3>
					</div>
					<table>
						<thead>
							<tr>
								<th>OrderNo</th>
								<th>Total Amt</th>
								<th>Status</th>
								<th>Order Time</th>
								<th>Thrift manager</th>
								<th>Thrifter </th>
							</tr>
						</thead>
						<tbody>
								{% for order in managerorders %}

								<tr>
									<td><a href="{% url 'plugmanager:orderlist' order.order.id %}" class="btn btn-sm btn-dark">{{order.order.id}}</a></td>
		
									<td>{{order.order.total_amt}}</td>
									<td><span class="status completed">{{order.order.order_status}}</span></td>
									<td>{{order.order.order_dt}}</td>
									<td>{{order.manager}}</td>
									<td>{{order.customer}}</td>
		
									
								</tr>
								{% endfor %}
				

						</tbody>
					</table>
				</div>
			</div>
			<div class="order_nav">
				<div class="orders_available">
					<div class="order_title">
						<h3>Admin orders</h3>
					</div>
					<table>
						<thead>
							<tr>
								<th>OrderNo</th>
								<th>Total Amt</th>
								<th>Status</th>
								<th>Order Time</th>
								<th>Thrift manager</th>
								<th>Thrifter </th>
							</tr>
						</thead>
						<tbody>

							{% for order in orders %}
							{% for ordered in ordered %}
	
							{% if ordered.order.id == order.order.id %}
	
	
							<tr>
								<td><a href="{% url 'customer:Thrift-orderlist' ordered.order.id %}" class="btn btn-sm btn-dark">{{ordered.order.id}}</a></td>

								<td>{{ordered.order.total_amt}}</td>
								<td><span class="status completed">{{ordered.order.order_status}}</span></td>
								<td>{{ordered.order.order_dt}}</td>
								<td>{{ordered.manager}}</td>
								<td>
									
									{{ordered.customer}}
								</td>
							</tr>
							{% endif %}
							{% endfor %}
							{% endfor %}



						</tbody>
					</table>
				</div>
			</div>



{% endblock %}





<!--

							{% for order in orders %}
							{% for ordered in ordered %}
	
							{% if ordered.order.id == order.order.id %}
	
	
							<tr>
								<td><a href="{% url 'customer:Thrift-orderlist' ordered.order.id %}" class="btn btn-sm btn-dark">{{ordered.order.id}}</a></td>

								<td>{{ordered.order.total_amt}}</td>
								<td><span class="status completed">{{ordered.order.order_status}}</span></td>
								<td>{{ordered.order.order_dt}}</td>
								<td>{{ordered.manager}}</td>
								<td>
									
									{{ordered.customer}}
								</td>
							</tr>
							{% endif %}
							{% endfor %}
							{% endfor %}


-->

templates/product_available_list.html
{% extends 'index.html' %}

{% load static %}
	{% block content %}
	
	{% block css %}
    <link rel="stylesheet" type="text/css" href="{%static 'styles/product_available_list.css'%}">
	<link rel="stylesheet" href="{%static 'styles/sidebarfilter.css'%}">

	{% endblock %}

	{% block js %}
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'product-filter.js' %}"></script>
<script type="text/javascript" src="{% static 'sidebarfilter.js' %}"></script>
		{% endblock %}
 
	
<section id="featureds">

	<div class="container swiper">
  
		<main class="cd-main-content" style="margin-bottom: 40px;">


			<div class="sidebar-filter">
				<form>
					<div class="sidebar-filter-block">
						<h4>select price</h4>
	
						<ul class="sidebar-filter-content sidebar-filters list">
							<li>
								<input type="range" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} id="rangeInput" oninput="maxPrice.value=this.value" />
								<p>{{minMaxPrice.price__min}}-{{minMaxPrice.price__max}}</p>
							
								Max: <input type="number" value="{{maxMinPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} class="form-control" id="maxPrice" onkeyup="rangeInput.value=this.value" id="maxPrice" />
				  <button  data-limit="{{product.id}}" id="priceFilterBtn_product_branch">Filter</button>
							</li>
						</ul> <!-- sidebar-filter-content -->
					</div> <!-- sidebar-filter-block -->
			<div class="sidebar-filter-block">
						<h4>Choose sizes</h4>
	
						<ul class="sidebar-filter-content sidebar-filters list">
				{% for size in sizes %}
	
							<li>
	
				  <input class=" filter-checkbox filter " data-filter="size" value="{{size.size__id}}" type="checkbox" id="{{size.size__title}}" />&nbsp;
				  <label class="checkbox-label" for="{{size.size__title}}">{{size.size__title}}</label>
	
							</li>
				{% endfor %}
	
						</ul> <!-- sidebar-filter-content -->
					</div> <!-- sidebar-filter-block -->
			<div class="sidebar-filter-block">
						<h4>Choose color</h4>
	
						<ul class="sidebar-filter-content sidebar-filters list">
				{% for color in colors %}
	
							<li>
				  <input class=" filter-checkbox filter " data-filter="color" value="{{color.color__id}}" type="checkbox"  id="{{color.color__title}}" />&nbsp;
				  <label class="checkbox-label " style="background-color:{{color.color__color_code}};cursor: pointer; width: 20px;height: 10px;border: radius 10px;" for="{{color.color__title}}">
	
	
					  
							</li>
				{% endfor %}
						</ul> <!-- sidebar-filter-content -->
					</div> <!-- sidebar-filter-block -->
			<div class="sidebar-filter-block">
						<h4>Choose Type</h4>
	
						<ul class="sidebar-filter-content sidebar-filters list">
				{% for product in products %}
	
							<li>
				  <input class=" filter-checkbox filter" data-filter="product" value="{{product.product__id}}" type="checkbox" id="{{product.product__title}}"/>&nbsp;
				  <label class="checkbox-label" for="{{product.product__title}}">{{product.product__title}}</label>
	
					  
							</li>
				{% endfor %}
						</ul> <!-- sidebar-filter-content -->
					</div> <!-- sidebar-filter-block -->
			<div class="sidebar-filter-block">
						<h4>Choose Brand</h4>
	
						<ul class="sidebar-filter-content sidebar-filters list">
				{% for brand in branded %}
	
							<li>
				  <input class=" filter-checkbox filter" data-filter="brand" value="{{brand.brand__id}}" type="checkbox" id="{{brand.brand__title}}"/>&nbsp;
				  <label class="checkbox-label" for="{{brand.brand__title}}">{{brand.brand__title}}</label>
	
					  
							</li>
				{% endfor %}
						</ul> <!-- sidebar-filter-content -->
					</div> <!-- sidebar-filter-block -->
				
				</form>
	
				<a href="#0" class="cd-close">Close</a>
			</div> <!-- sidebar-filter -->
	
			<a href="#0" class="sidebar-filter-trigger">Filters</a>
		</main> <!-- cd-main-content --> 
		<div  id="filteredProducts_product_branch">

		{% for product in datazing %}
	
		<h1 class="headings" style="font-size: 25px;">{{product.product.title}}</h1>
	
		{% endfor %}
	
		<div class="productcat-container">
			{% for product in data %}
	
			 <div class="box">
				<div class="box1">
					<div class="icons">
						<a href="#" class="fas fa-heart"></a>
						<a href="#" class="fas fa-share"></a>
						<a href="/product_detail/{{product.id}}" class="fas fa-eye"></a>
					</div>
				<div class="image">
					<a href="/product_detail/{{product.id}}"><img src="/media/{{product.image}}" class="card-img-top" alt="{{product.title}}"></a>
				</div>
				<div class="content">
				  <h3 class="card-text"><a href="/product_detail/{{product.id}}">{{product.title}}</a></h3>
				  <p>$ <span class="product-price-{{product.id}}">{{product.price}}</span></p>
				  <div class="content-icons">
					<a href="#" class="fas fa-heart"></a>
					<a href="#" class="fas fa-share"></a>
					<a href="/product_detail/{{product.id}}" class="fas fa-eye"></a>
				  </div>
				  <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				  <input type="hidden" class="product-image-{{product.id}}" value="{{product.image}}" />
				  <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				  <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
					<input type="hidden" class="product-size-{{product.id}}" value="{{product.size}}" />
						  <input type="hidden" class="product-color-{{product.id}}" value="{{product.color}}" />
						  <input type="hidden" class="product-manager-{{product.id}}" value="{{product.product_manager}}" />
				  <button  class="btn  add-to-cart" data-index="{{product.id}}" type="button" id="addToCartBtn">Add to cart</button>
				</div>
				</div>
			 </div>
			 {% endfor %}
	
			 
		  </div>
	    </div>
	 
	  </div>
  </section>


  {% endblock %}

</body>
</html>